# Generated by Django 2.2 on 2021-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_enrty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrty',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
